# RUN TO CREATE DEV ENVIRONMENT

version: '3.8'

networks:
  tide-network:
    driver: bridge

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tide_users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tide-network

  user-service:
    image: 192.168.1.18:5000/tide-user-service:dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tide_users
    depends_on:
      - db
      - tide-eureka
    networks:
      - tide-network

  tide-eureka:
    image: 192.168.1.18:5000/tide-eureka:dev
    ports:
      - "8761:8761"
    networks:
      - tide-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pgdata